### ISSUE TITLE
7.1 Release Prep Unit Test Failures & Errors

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/DataVec#126]
API
  TestJsonYaml.testToFromJsonYaml:146 » IndexOutOfBounds Index: 14, Size: 14
  TestTransforms.testRemoveColumnsTransform:204 » IndexOutOfBounds Index: 4, Siz...

Spark
  TestRecordReaderBytesFunction.testRecordReaderBytesFunction:82 » UnsatisfiedLink
  TestRecordReaderFunction.testRecordReaderFunction:59 » Spark Job aborted due t...
org.datavec.spark.functions.TestSequenceRecordReaderBytesFunction.testRecordReaderBytesFunction(org.datavec.spark.functions.TestSequenceRecordReaderBytesFunction)

**Comment by AlexDBlack** [comment]
First 2 fixed here: https://github.com/deeplearning4j/DataVec/pull/127

@saudet Spark issues seem to be due to javacpp 1.2.6 upgrade? All spark tests pass after switching datavec-spark-image javacpp version back to 1.2.5.

![image](https://cloud.githubusercontent.com/assets/2360237/20700233/30020498-b660-11e6-9c4e-16454a08cccf.png)

**Comment by saudet** [comment]
Yes, issues with loading OpenCV...

**Comment by saudet** [comment]
The only test that is failing for me otherwise is this:
```
testLineReaderMetaData(org.datavec.api.records.reader.impl.LineReaderTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.datavec.api.records.reader.impl.LineReaderTest.testLineReaderMetaData(LineReaderTest.java:127)
```

**Comment by AlexDBlack** [comment]
@saudet JavaCPP 1.2.7 seems to have fixed those spark tests.

I'm not seeing a failure on LineReaderTest.testLineReaderMetaData... is that still an issue?

**Comment by saudet** [comment]
@AlexDBlack Yes, still an issue, but looks like something with the class path

**Comment by AlexDBlack** [comment]
Ah, I was running in intellij. That probably explains the difference.

**Comment by nyghtowl** [comment]
All tests passing on this repo now. Closing but feel free to reopen if still seeing issues.
